version: "3.8"
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - uwsgi
      - --ini
      - uwsgi.ini
      - --http
      - :8000
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/usr/app/db.sqlite3
